name: swing_app
description: A new Flutter project

# This section defines the version and environment settings.
version: 1.0.0
environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Updated version
  http: ^0.13.4
  cupertino_icons: ^1.0.8
  lib: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
